name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - run: git checkout ${{GITHUB_BASE_REF}}
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
